const swaggerAutogen = require('swagger-autogen')({ openapi: '3.0.0' });

const doc = {
  info: {
    title: 'BusNirikshan API',
    description: 'API documentation for the BusNirikshan backend. Autogenerated endpoints.',
  },
  servers: [
    {
      url: 'http://localhost:5000',
      description: 'Development server'
    },
    {
      url: 'https://busnirikshanapi.mauliksharma.org',
      description: 'Production server'
    }
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      }
    }
  },
  security: [{ bearerAuth: [] }]
};

const outputFile = './swagger-output.json';
const routes = ['./server.js'];

// Run swagger-autogen
swaggerAutogen(outputFile, routes, doc).then(() => {
    console.log("Swagger documentation generated successfully.");
});
